### ISSUE TITLE
Single Example

### ISSUE THREAD

**Issue by rafaellupo** [gentor/activecampaign#1]
My dear friend,

Would you kindly provide one single API call example from a controller ?

It can be the account view method. Please, this integration with active campaign is driving me crazy.

**Comment by studiovlijmscherp** [comment]
I'm struggling too. Now calling the class directly from my controller:
$ac = new ActiveCampaign('$url', '$key');

Sure would love to see how the Facade is put into use.

**Comment by gentor** [comment]
Sorry for my late reply ;)

To view an account just call: `AC::contactView($id)`
